### ISSUE TITLE
Signed Cookies

### ISSUE THREAD

**Issue by leonelgalan** [dylanvaughn/aws_cf_signer#6]
[AWS announced signed cookies support](https://aws.amazon.com/blogs/aws/new-amazon-cloudfront-signed-cookies-for-private-content/) a while back, a good use-case for them is to [provide access to multiple restricted files](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-choosing-signed-urls-cookies.html).

The implementation is very similar to signed URLs, but trying to get the values from aws_cf_signer and sending them using `cookies` in Rails didn't work. I added some `attr_reader`s to signer and:

## Controller

```ruby
domain = 'd1z0hf3p8j4xla.cloudfront.net'
key = 'pk-APKAJVJCJ35TMRTR5DYQ.pem'
signer = AwsCfSigner.new(Rails.root.join(key).to_s)
url = signer.sign("http://#{domain}/folder2/stealz_logo3.png", ending: 2.day.from_now)

{ 'CloudFront-Expires' => signer.expires_at,
  'CloudFront-Signature' => signer.signature,
  'CloudFront-Key-Pair-Id' => signer.key_pair_id }.each do |key, value|
  cookies[key] = { value: value, domain: domain, httponly: true, secure: true }
end
```

That `url` being set works as intended, the problem is solely when setting the cookies and trying to read the object without the signed url.

## Response
Even I see the cookies coming down on the response (Google Chrome Developer Tools), I cannot find the cookies when I search for _cloudfront.net_ in my cookies and I get a 403 Forbidden (`<?xml version="1.0" encoding="UTF-8"?><Error><Code>MissingKey</Code><Message>Missing Key-Pair-Id query parameter or cookie value</Message></Error>`) when linking to the image.

### Headers
```
...
Set-Cookie:CloudFront-Signature=NhbepC75buSNRcMiBDvK1T724whA%7EX88pzmEHJ%7E98aVFNMr0KtF3TRWsoD%7ET6Hr%7EEvJqehl6oFUCav4mJUFiSmL4i6Yf6aWkuTqnWWqUyDGqlm9Uq%7EpzIBAXu9Xpt54r3qxwxqTYE7%7ENDyfa1CJiTg1u7sUY266vQPFQqjZ3k5TETupabYFm4udKZCcIkaGtz2Ut2v8qrnM-gg0sTrPoamKBGcv0sAoZMhm%7EG5rF5%7EiEuOz0swo7vHga2dhA06phXup-bGjsoLnd2la-n0Xj%7E8aV6bwpvPpMpPbMTsN4Gr6Cu06iijpUYEUQ4VhDwgYZ4GRSOQWhPC22GtlHLb9o1g__; domain=d1z0hf3p8j4xla.cloudfront.net; path=/; secure; HttpOnly

Set-Cookie:CloudFront-Key-Pair-Id=APKAJVJCJ35TMRTR5DYQ; domain=d1z0hf3p8j4xla.cloudfront.net; path=/; secure; HttpOnly

Set-Cookie:CloudFront-Expires=1428865213; domain=d1z0hf3p8j4xla.cloudfront.net; path=/; secure; HttpOnly
...
```

### Body
```html
...
<img src="http://d1z0hf3p8j4xla.cloudfront.net/folder2/stealz_logo3.png " alt="Stealz logo3">
...
```

**UPDATE**: Corrected response when requesting image.

**Comment by fcheung** [comment]
You can only set cookies for the domain your content is being served from - the browser won't let www.example.com set cookies that are sent to foo.cloudfront.net. In addition you're marking the cookie as secure (only send over https) but you're making a plain http request.

The easiest way around this is to use a CNAME so that your cloud front content appears to come from the same domain as your applications. There are some limitations around https & CNAMEs for cloud front - you have to either use SNI or pay extra though. The alternative involves using a cloud front behaviour to send some requests to your app - cookies sent then will appear to come from cloud front so the browser will accept them

**Comment by dylanvaughn** [comment]
@leonelgalan, does @fcheung comment fix your issue?  I'll go ahead and close this - feel free to re-open.
